package com.android.record.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.android.record.bean.user;
import com.android.record.bean.SwipeCardBean;
import com.android.record.bean.Diary;

import com.android.record.greendao.userDao;
import com.android.record.greendao.SwipeCardBeanDao;
import com.android.record.greendao.DiaryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig swipeCardBeanDaoConfig;
    private final DaoConfig diaryDaoConfig;

    private final userDao userDao;
    private final SwipeCardBeanDao swipeCardBeanDao;
    private final DiaryDao diaryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(userDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        swipeCardBeanDaoConfig = daoConfigMap.get(SwipeCardBeanDao.class).clone();
        swipeCardBeanDaoConfig.initIdentityScope(type);

        diaryDaoConfig = daoConfigMap.get(DiaryDao.class).clone();
        diaryDaoConfig.initIdentityScope(type);

        userDao = new userDao(userDaoConfig, this);
        swipeCardBeanDao = new SwipeCardBeanDao(swipeCardBeanDaoConfig, this);
        diaryDao = new DiaryDao(diaryDaoConfig, this);

        registerDao(user.class, userDao);
        registerDao(SwipeCardBean.class, swipeCardBeanDao);
        registerDao(Diary.class, diaryDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        swipeCardBeanDaoConfig.clearIdentityScope();
        diaryDaoConfig.clearIdentityScope();
    }

    public userDao getUserDao() {
        return userDao;
    }

    public SwipeCardBeanDao getSwipeCardBeanDao() {
        return swipeCardBeanDao;
    }

    public DiaryDao getDiaryDao() {
        return diaryDao;
    }

}
