package com.android.record.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.android.record.bean.SwipeCardBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SWIPE_CARD_BEAN".
*/
public class SwipeCardBeanDao extends AbstractDao<SwipeCardBean, Void> {

    public static final String TABLENAME = "SWIPE_CARD_BEAN";

    /**
     * Properties of entity SwipeCardBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Position = new Property(0, int.class, "position", false, "POSITION");
        public final static Property Url = new Property(1, String.class, "url", false, "URL");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property CurrentTime = new Property(3, long.class, "currentTime", false, "CURRENT_TIME");
    }


    public SwipeCardBeanDao(DaoConfig config) {
        super(config);
    }
    
    public SwipeCardBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SWIPE_CARD_BEAN\" (" + //
                "\"POSITION\" INTEGER NOT NULL ," + // 0: position
                "\"URL\" TEXT," + // 1: url
                "\"NAME\" TEXT," + // 2: name
                "\"CURRENT_TIME\" INTEGER NOT NULL );"); // 3: currentTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SWIPE_CARD_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SwipeCardBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getPosition());
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(2, url);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
        stmt.bindLong(4, entity.getCurrentTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SwipeCardBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getPosition());
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(2, url);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
        stmt.bindLong(4, entity.getCurrentTime());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public SwipeCardBean readEntity(Cursor cursor, int offset) {
        SwipeCardBean entity = new SwipeCardBean( //
            cursor.getInt(offset + 0), // position
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // url
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.getLong(offset + 3) // currentTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SwipeCardBean entity, int offset) {
        entity.setPosition(cursor.getInt(offset + 0));
        entity.setUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCurrentTime(cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(SwipeCardBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(SwipeCardBean entity) {
        return null;
    }

    @Override
    public boolean hasKey(SwipeCardBean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
